### PR TITLE
LPS-153827 master

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @dacousalr 

could you please review my fix?

Thanks for helping creating the Wrapper class.

https://issues.liferay.com/browse/PTR-3093
https://issues.liferay.com/browse/LPS-153827

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:relevanr

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/8244.

**Pull request closed without merging**
