### PR TITLE
LPS-137328 We should only care when the string is actually null. An e…

### PR DESCRIPTION
**Pull request by brianikim**
…mpty string implies user wants to delete the friendlyURL.

https://issues.liferay.com/browse/LPS-137328

Hey @dacousalr ,

The root cause of the behavior is in FriendlyURLEntryLocalServiceImpl which is why I am sending this PR to you even though the sub issues are related to Commerce.

I'd like this fix merged as soon as possible so I can work on the COMMERCE ticket for the sub issues.

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
Hi @brianikim,

This solution seems to be incomplete. After testing it, the issue can still be reproduced.

Could you help me understand the complete fix approach you are proposing?

Thanks in advance

**Comment by brianikim** [comment]
Hello @dacousalr ,

We can close this ticket. I am able to contain the fix within the Commerce modules. https://github.com/liferay-commerce/liferay-portal/pull/1576

**Pull request closed without merging**
