### PR TITLE
[TS] LPS-95585 Only Global group is accesible from page templates

### PR DESCRIPTION
**Pull request by balazssk**
Hi @dacousalr 
This is an alternative way for the Page Template problem.
Instead of removing the AssetSelector from the WCD Setup this adapts the logic of using nulls instead of page templates as parameter for isGroupAccessible.

This will let us select Global assets.
Of course, this will need a little tweak on the LPS description.

https://issues.liferay.com/browse/LPS-95585

Thanks,

### CODE REVIEW

**Comment by balazssk** [comment]
Hi @dacousalr ,
I've rephrased the LPS to better reflect the issue we are facing and closed #119 . I think we should go forward with this as a final solution.

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by balazssk** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
Hi @balazssk,

I would like to pass this PR as is but some changes should have to be added to the asset browser in order to set the proper groupId among the filterGroupIds to show the global contents to select. Currently no group is filtered and no Web Content is selectable so users are forced to change the filter to Global or All for these Global Web Contents to be shown.

Please, let me know if you need additional clarifications about this.

**Pull request closed without merging**
