### PR TITLE
LPS-126484 expandedEntriesPerFeed should allow 0.

### PR DESCRIPTION
**Pull request by brianikim**
Sending directly to you to address issue as discussed in PTR-2176 for LPS-108351.

https://issues.liferay.com/browse/LPS-126484

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Hello @dacousalr ,

Let me know if there are any issues with the PR>

Sincerely,
Brian Kim

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
ci:forward

**Pull request closed without merging**
