### PR TITLE
LPS-94656 Add escape methods to improve security.

### PR DESCRIPTION
**Pull request by natocesarrego**
Hi @dacousalr,

I'm sending this pull request to you as agreed [here](https://github.com/dacousalr/liferay-portal-ee/pull/90#issuecomment-486795311). This implementation took a little longer than expected, but here it is. 🙂 

Thanks in advance for your review!

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/2378.

**Pull request closed without merging**
