### PR TITLE
[TS] LPS-103737

### PR DESCRIPTION
**Pull request by balazssk**
Hi @dacousalr ,

I've finished the language portlet fix we've discussed on https://issues.liferay.com/browse/PTR-1281.

> Language Portlet should only display a subset of it's configured languages that match the site's current languages. On the view side, this is easy to do. On the configuration side, we can also limit the current languages can also be filtered down so upon update we will follow the site's rules.

Can you please review?
https://issues.liferay.com/browse/LPS-103737

Thanks,
Balázs

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Hi @balazssk,

The approach is OK but I am a bit concerned about whether the transformation to sets would respect the original order. Could you double-check this?

**Comment by balazssk** [comment]
Hi @dacousalr ,
You are correct, the original order is not kept. I'll look into this.

**Comment by balazssk** [comment]
Hi @dacousalr ,
I've noticed that the site's default language is treated a bit differently in the Language Portlet's configuration. At first, it appears at the top of the Current Languages (this comes from LanguageImpl#_createGroupLocales), but once moved to available, it is not ordered to the top.

The trick here is that available languages are sorted before displaying in SiteNavigationLanguageDisplayContext#getAvailableLanguageIdKVPs, but the current languages are not sorted in SiteNavigationLanguageDisplayContext#getCurrentLanguageIdKVPs. The reasoning behind this might have been to preserve the top position of the default language. However, once the default language is moved to available,  saved, and back to current, it will be appended to the end of the list.

After realising this, I'd like to ask if having the default language at the top of both selectors a requirement for this portlet?
If it is not, we can sort the current languages like the available ones.
However if it is a requirement, we might need to create a new ordering algorithm for both selectors. (Similar how LanguageImpl#_createGroupLocales puts the default locale first)

What do you think?

**Comment by dacousalr** [comment]
Hi @balazssk,

The default language at the top is only valid when there is no previous configuration.

In presence of previous configuration, the order of current languages should be respected since it can be established by users manually so that this saved order can be preserved.

In presence or absence of previous configuration, the order of available language is the alphabetical order of the values including the default language.

**Comment by balazssk** [comment]
I see, so we can't use SetUtil.intersect to find the current languages as it will inevitably change the order.

**Pull request closed without merging**
