### PR TITLE
[TECHNICAL SUPPORT] LPS-115491 Summary field value is lost when default locale is changed

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,
[LPS-115491](https://issues.liferay.com/browse/LPS-115491),
We do not handle the changeable default language feature inside journal-portlet. I attached a listener to defaultLocaleChange and also created a new event, that I fire from ddm_form.js. This is to sync the defaultLanguage from the structure-definition. It still defaults to the defaultLocale inside the theme-display.

Please review it,

Thanks

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/1088. [See changes here.](https://github.com/dacousalr/liferay-portal/compare/3b66c90bccf2~2...3b66c90bccf2)

**Pull request closed without merging**
