### PR TITLE
LPS-109848

### PR DESCRIPTION
**Pull request by bakayattila**
hi @dacousalr,
I re-implemented the robots.txt wildcard based on your response on the last pull request.
could you review it?

https://issues.liferay.com/browse/LPS-109848
Best,
Attila

### CODE REVIEW

**Comment by bakayattila** [comment]
https://github.com/dacousalr/liferay-portal/pull/188

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Pull request closed without merging**
