### PR TITLE
LPP-42880 Categories Associated Asset Types are not being saved or modified correctly

### PR DESCRIPTION
**Pull request by thuycao-gs**
Hi @dacousalr,
I have updated my PR.
Thank you.

### CODE REVIEW

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by thuycao-gs** [comment]
Hi @dacousalr,

How's the review going? Any update?

**Comment by rolandpakai** [comment]
Hi @dacousalr 

could you please review this PR?

Thanks, Roland

**Comment by huynguyen-liferay** [comment]
Hi @dacousalr,

  Could you please review this PR ?

Thanks, Huy

**Comment by dacousalr** [comment]
Hi,

This issue is being currently analyzed in PTR-2710 since, although the PR fixes the original issues, it opens some new ones.

Best,
Daniel

**Pull request closed without merging**
