### PR TITLE
LPS-114083 Handle duplicate names in upgrade Layout Prototype

### PR DESCRIPTION
**Pull request by achaparro**
Hey @dacousalr, here you have the pull with the changes requested.

@Samziemer please, take a look at the new changes.

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Same errors found here too:
https://liferay.slack.com/archives/CLCD3DQLF/p1592247756212200

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/1210.

**Pull request closed without merging**
