### PR TITLE
Lps 109019

### PR DESCRIPTION
**Pull request by balazssk**
Hi @dacousalr ,

fixes SF from https://github.com/dacousalr/liferay-portal/pull/261
I've made a change to the tests somewhat unrelated to this fix in 818edb6 hope it's ok.

Can you please review?
https://issues.liferay.com/browse/LPS-109019

Thanks,
Balázs

### CODE REVIEW

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/liferay/liferay-portal/pull/3884. [See changes here.](https://github.com/dacousalr/liferay-portal/compare/a22761d45d5b~2...a22761d45d5b)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/1635. [See changes here.](https://github.com/dacousalr/liferay-portal/compare/a22761d45d5b~2...a22761d45d5b)

**Pull request closed without merging**
