### PR TITLE
LPS-110508 Open in full view

### PR DESCRIPTION
**Pull request by balazssk**
Hi @dacousalr ,

Changed the Web Content Display's View History icon to open in full view instead of a popup.

Can you please review?
https://issues.liferay.com/browse/LPS-110508

Thanks,
Balázs

### CODE REVIEW

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
The test:relevant issue looks like https://liferay.slack.com/archives/C04D8HMEF/p1585121492001200

> hey all, in todays master, if we execute gradlew clean deploy it will remove the bnd for that module. So….mostly FYI

**Comment by dacousalr** [comment]
Yes, it is very likely. I will re-launch the relevant tests tomorrow. If they pass, I will do ci:forward

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
ci:forward

**Comment by dacousalr** [comment]
ci:forward

**Pull request closed without merging**
