### PR TITLE
[TS] LPS-92704

### PR DESCRIPTION
**Pull request by balazssk**
Hi @dacousalr ,

Sorry about the SF error, fixed it from https://github.com/dacousalr/liferay-portal/pull/182

### CODE REVIEW

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Hi @balazssk,

I am afraid I cannot pass the PR. The reason is that getLayoutsCount method is called without passing the (layout) type, which can leave out valid results.

Maybe you can take the following approach https://github.com/liferay/liferay-portal-ee/pull/18205/commits/3292f3fbd9ef4eff0a573186dd1e87ae31f00016

**Pull request closed without merging**
