### PR TITLE
[TS] LPS-98290 Journal Article images are not transfered when using the jsonws / add-article method

### PR DESCRIPTION
**Pull request by peterpetrekanics**
Hi Daniel,

Please review my fix.
This change is planned to be backported to 7.0.
If you agree with this change, please forward it to the next approver,
Thank you, Peter

### CODE REVIEW

**Comment by peterpetrekanics** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Hi @peterpetrekanics,

I have the following considerations:
1) I do not see any reason why we should address the JSONWS case and the local case differently.
2) The maximum file size is not being validated.
3) I would prefer a solution similar to how a Journal Article is added via UI, that is, by creating temp images and then persist them definitely when calling to the method format.

Could you review these points?

Thanks

**Comment by peterpetrekanics** [comment]
Dear @dacousalr,

Thank you for checking the pull request.
I have reviewed your points and indeed it would be nice to change the code based on your suggestions.

The maximum file size validation was not part of the LPS-54107 fix that was my starting point of this current fix, so that would be an addition.
If I am not separating the JSONWS case from the local case that means a lot of additional testing, also it would take much time to change the logic and have a temp image created first.

However the customer is waiting for a solution, so my question is if I can provide the fix in a form of an SDH fix to the customer?

Many thanks,
Peter

**Comment by dacousalr** [comment]
Hi @peterpetrekanics,

The SDH would be acceptable but it should include the maximum file size validation since that check is being done in com.liferay.journal.web.internal.upload.ImageJournalUploadFileEntryHandler

**Comment by peterpetrekanics** [comment]
Thank you very much!

**Pull request closed without merging**
