### PR TITLE
LPS-132408 View in context link is missing in My Workflow Tasks review of web content with a display page template

### PR DESCRIPTION
**Pull request by MarcellGyopos**
Hi @dacousalr ,
Could you please review this pull request?
https://issues.liferay.com/browse/PTR-2432
According to your suggestions I have involved the article groupId into the condition. I hope I understood your opinion well.
I know It's seems like code duplication, but the other option is to extend the _isShowDisplayPage method and every other methods which are used in this method, I think It would be an overkill. With this change the workflow link works well for me. I see there are other LPPs pending on this LPS/PTR which I have not tested bc of lack of time. I hope you know more this module and you are able to decide the solution will work as expected in every possible case.
Thank you and best regards,
Marci

### CODE REVIEW

**Comment by MarcellGyopos** [comment]
ci:test:relevant

**Comment by MarcellGyopos** [comment]
ci:test:sf

**Comment by MarcellGyopos** [comment]
ci:test:relevant

**Comment by MarcellGyopos** [comment]
Hi @dacousalr ,
I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.
Thank you and best regards,
Marci

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/4741. [See changes here.](https://github.com/dacousalr/liferay-portal/compare/3861769ed8e2~3...3861769ed8e2)

**Pull request closed without merging**
