### PR TITLE
LPS-116559

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-116559

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
ci:forward

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/dacousalr/liferay-portal/pull/256. [See changes here.](https://github.com/dacousalr/liferay-portal/compare/4f4bad92c33a~1...4f4bad92c33a)

**Pull request closed without merging**
