### PR TITLE
LPS-132376

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/LPS-132376

Revert of the commits as discussed in PTR-2441(https://issues.liferay.com/browse/PTR-2441)

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/4593. [See changes here.](https://github.com/dacousalr/liferay-portal/compare/3ac434ee5cd1~1...3ac434ee5cd1)

**Pull request closed without merging**
