### PR TITLE
LPS-131800 General error message is displayed when publishing a web content with an incomplete link in the field

### PR DESCRIPTION
**Pull request by MarcellGyopos**
Hi @dacousalr 
Could you please review this pull request?
Thank you and best regards,
Marci

### CODE REVIEW

**Comment by MarcellGyopos** [comment]
ci:test:relevant

**Comment by MarcellGyopos** [comment]
ci:test:sf

**Comment by MarcellGyopos** [comment]
Hi @dacousalr ,
I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.
Thank you and best regards,
Marci

**Comment by MarcellGyopos** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
ci:forward

**Pull request closed without merging**
