### PR TITLE
LPS-135087 Integration Tests

### PR DESCRIPTION
**Pull request by mbowerman**
Adding integration tests to LPS-135087 per @brianchandotcom's [request](https://github.com/brianchandotcom/liferay-portal/pull/104420#issuecomment-880876688).

Also, in the third commit, I fixed a bug that I discovered, which was causing some of the existing integration tests to fail.

https://issues.liferay.com/browse/LPS-135087

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/dacousalr/liferay-portal/pull/324.

**Pull request closed without merging**
