### PR TITLE
LPS-95644 Expired Web Contents have incorrect status in search index

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-95644](https://issues.liferay.com/browse/LPS-95644)

Hi Daniel,

I hope you can review my changes.

The issue is that at scheduled Web Content expiration the updated index documents are put into the SYSTEM index.

ElasticsearchIndexWriter.updateDocuments() calls searchContext.getCompanyId() when composing the indexName. Previously, the value of searchContext._companyId is set based on what comes from the IndexableActionableDynamicQuery. That is all what is important about my changes.

Pleas let me know if there is anything I can help you with.

Thank you,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:search

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73292.

**Pull request closed without merging**
