### PR TITLE
[TS] LPS-92704

### PR DESCRIPTION
**Pull request by balazssk**
Hi @dacousalr ,
I've rebased this from https://github.com/dacousalr/liferay-portal/pull/187
The 50k number limit works perfectly, sadly the 50MB limit is troublesome if there are a lot of available languages and a lit of journal articles for a single page (in my tests, 52-53MB was the cut with all default 13 languages present in the site). I can't think of a any improvement to approximate what will be the actual size of the xml as pure string.

Can you please review?
https://issues.liferay.com/browse/LPS-92704

Thanks,
Balázs

### CODE REVIEW

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
resolved bnd conflicts

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
Hi @dacousalr ,
I know you might be occupied with various other higher priority tasks. If you don't have time for this at the moment can you please share a timeline when you'll be able to pick this up?
Thank you

**Comment by dacousalr** [comment]
Hi @balazssk,

Firstly, sorry for the delay(s) in this review.

My goal is to review it next week.

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/955.

**Pull request closed without merging**
