### PR TITLE
LPS-101910 Add align class to image in RSS Feed

### PR DESCRIPTION
**Pull request by orsolyalukacs**
Hi @dacousalr,

I have updated the PR according to https://github.com/dacousalr/liferay-portal/pull/147
Please review these changes.

Thanks,
Orsi

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Hi @orsolyalukacs,

If this fix has to be backported to 7.0, please, be aware of the fact that flex cannot be used in that version due to IE limitations.

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78713. [See changes here.](https://github.com/dacousalr/liferay-portal/compare/fea36b353763~2...fea36b353763)

**Comment by orsolyalukacs** [comment]
Thank you, @dacousalr! I will take note of that if we are about to backport to 7.0.

**Pull request closed without merging**
