### PR TITLE
LPS-89352 Create view history configuration icon for edit_article view

### PR DESCRIPTION
**Pull request by balazssk**
Hi @dacousalr ,

https://issues.liferay.com/browse/LPS-89352

I've followed your suggestion from https://issues.liferay.com/browse/LPS-89352?focusedCommentId=1684105#comment-1684105 and added the new PCI to the edit_article view.

I have some questions, maybe you can help me out on them:
1. You mentioned that there is a possibility to customize this to appear on JournalContentPortlets as well, however I could not get that working with simply adding another javax.portlet.name. PortletConfigurationIconServiceReferenceMapper#map seems to limit it to one value. Should this be updated to use multiple ones?
2. I couldn't get this PCI to display on a JCP, I tried to use 
"javax.portlet.name=com_liferay_journal_content_web_portlet_JournalContentPortlet" with "path=/view.jsp", maybe I've got the how path works wrong, can you please explain it to me?

Thanks,

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Hi @balazssk,

I have reviewed the PR and I have detected that back button is not working. Could you review it, please?

1. As you mention, there is a limitation on which portlet a PCI can appear. In any case a PCI could be moved/put in another place by changing its properties.

2. Try with `path="-"`. It will appear in the portlet bar if the method isShow returns true. Unfortunately, there is no way to make it appear in the second kebap menu because it does not rely on PCIs but on a Dynamic Include. See https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-content-web/src/main/java/com/liferay/journal/content/web/internal/servlet/taglib/JournalContentPortletHeaderJSPDynamicInclude.java

**Comment by balazssk** [comment]
Hi @dacousalr ,
Can you please elaborate on the back button?
I've set up https://github.com/dacousalr/liferay-portal/pull/102/files#diff-f73db668d56d5f265eec6edc43503ddcR28 for the backURL to work, and in my tests the Portlet's back button is nacigating me back to the edit_article.jsp.
I've also checked the browser back button, and it is also navigating to the edit_article.jsp

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/pavel-savinov/liferay-portal/pull/312.

**Pull request closed without merging**
