### PR TITLE
[TS] LPS-98112 Add fileEntryId to JSON

### PR DESCRIPTION
**Pull request by balazssk**
Hi @dacousalr ,
If I'm correct, the source of this inconsistency is https://issues.liferay.com/browse/LPS-70955, where fileEntryId was added to the Image's content JSON.

Can you please review?
https://issues.liferay.com/browse/LPS-98112

Thanks,
Balázs

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
Hi @dacousalr ,
I don't see any connection between the failures and my changes, so I've restarted the tests

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
Hi @dacousalr ,
Seems like all the test failures were unrelated. Can you please check if the solution is ok as well?
Thanks

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76198.

**Pull request closed without merging**
