### PR TITLE
LPS-89507

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hello @dacousalr @jkappler,

This is my current implementation for the Site and Page Template issue and I wanted to get your feedback to make sure this is what you wanted. Additionally, I wanted to bring up some issues I'm facing with it currently.

1. When there is only a single dropdown menu item in the navigation menu, the button itself does not work (https://github.com/dacousalr/liferay-portal/commit/cee72321d31578b659c4e1a1c475db18865a1022). This can also be seen when going to **Page Fragments - Resources**.

2. I am unable to delete the previously created Widget Page Templates within a Site that is based off of a Site Template. There does not seem to be a differentiation between a LayoutPageTemplateEntry that is created from a Site Template and one created by importing from a LAR. I cannot safely remove the invalid entries without potentially losing other information. I'm not sure if this is something that is necessary to clean up but as it stands it will serve no purpose after this upgrade is run.

3. When exporting and importing a site that contains a Widget Page Template, both sites are tied to the same LayoutPrototype so any modifications on one site affects the other. This is not directly related to the issue at hand but something I noticed during my testing.

Please let me know your thoughts and what needs to be reworked with current implementation.

Thank you.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Thanks @jonathanmccann,

I hope to finish my review by Monday since tomorrow I will be on PTO.

**Comment by dacousalr** [comment]
Hi @jonathanmccann,

Unfortunately, I could not finish my review today as I expected.

I will update you tomorrow.

**Comment by dacousalr** [comment]
Hi @jonathanmccann,

The PR looks good and addresses all my concerns. However, it seems that the upgrade fails with PostgreSQL:
`com.liferay.portal.kernel.upgrade.UpgradeException: org.postgresql.util.PSQLException: ERROR: operator does not exist: boolean = integer_  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts._ `

Could you take a look at it?

Thanks in advance

**Comment by jonathanmccann** [comment]
https://github.com/dacousalr/liferay-portal/pull/108

**Pull request closed without merging**
