### PR TITLE
LPS-108211

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @dacousalr 

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Hi @dacousalr 

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by dacousalr** [comment]
Hi @IstvanD,

Did you do some testing with xml.sitemap.index.enabled=false?

**Comment by IstvanD** [comment]
Hi @dacousalr,

I'm checking it now.

**Comment by dacousalr** [comment]
Closing this while reviewing the subcase xml.sitemap.index.enabled=false

**Pull request closed without merging**
