### PR TITLE
LPS-79390 remove distinct clause to improve performance

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test

**Comment by dacousalr** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dacousalr** [comment]
ci:retest

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/1554. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
