### PR TITLE
[TECHNICAL-SUPPORT] LPS-88316

### PR DESCRIPTION
**Pull request by Alec-Shay**
/cc @SamZiemer @jkappler 

Resent from: https://github.com/dacousalr/liferay-portal/pull/79

> Relevant tickets:
> 
> https://issues.liferay.com/browse/LPP-32287
> https://issues.liferay.com/browse/LPS-88316
> 
> Using the "View in Context" link under My Workflow Tasks for a pending article (with a configured display page) does not work if there are no approved versions of that article.
> 
> This is due to changes to both the getActualURL() and getJournalArticleLayout() methods in two previous changes:
> 
> liferay@ffc21d1#diff-88404608066b298ac8f681687363f86b
> liferay@f418247#diff-88404608066b298ac8f681687363f86b
> 
> With these changes, only approved versions can be viewed in context this way. However, we believe this is not correct, as it renders the "View in Context" link for workflow tasks non-functional unless there are already previously approved versions.

It seems that to prevent a regression with unapproved versions being viewed via the URL, we had to implement a new API in `JournalArticleService`, so hopefully that is acceptable in this case. I noticed that ant and gradle both didn't report the minor version increment I expected with adding that, but I am hoping CI testing will indicate that difference.

I'm sending this operating under the (default) assumption for us that this is a bug. However I'll also reply to your comment on the LPS, and we can still open a PTR if you would prefer.

Please let me know if there are any issues or concerns with this. Thank you!

### CODE REVIEW

**Comment by Alec-Shay** [comment]
ci:test

**Comment by dacousalr** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dacousalr** [comment]
Hi @Alec-Shay,

It seems that the code makes an assumption that the content reviewers (isContentReviewer) are the only ones to be checked. However, other roles, which can be OTB or custom, can also be configured to be assigned to a Workflow Task.

In addition to this, I think that it would not be necessary to add a new method to the API since the null checks could be detected through NoSuch exceptions and all the permission checks could be performed within the component although the code turned out to be a little bit less readable.

Could you review these two points?

**Comment by Alec-Shay** [comment]
Hello @dacousalr,

I will look into revising the solution to make sure other roles with permissions can view the content appropriately.

However, I'm not sure what you mean by adding the permission checks within the component. We tried fixing it from the component originally (https://github.com/dacousalr/liferay-portal/pull/84) but we didn't have access to the permission checker from there so I'm not sure how we could do it there. What less readable way are you referring to?

**Comment by Alec-Shay** [comment]
Thanks for your response @dacousalr. I am getting back to this now and hope to have changes ready soon.

**Pull request closed without merging**
