### PR TITLE
[TECHNICAL SUPPORT] LPS-123640 Miller column should scroll horizontally when the page tree loads

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,

[LPS-123640](https://issues.liferay.com/browse/LPS-123640)
Please review my changes.

Thanks,

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/3021.

**Pull request closed without merging**
