### PR TITLE
LPS-90127 Asset Publisher should use Live class types if asset is not staged

### PR DESCRIPTION
**Pull request by balazssk**
Hi @dacousalr ,

Can you please review?
https://issues.liferay.com/browse/LPS-90127

Thanks,

### CODE REVIEW

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Hi @balazssk,

Did you test this in a Remote Staging scenario?

**Comment by balazssk** [comment]
Hi @dacousalr ,
We've discussed the idea of remote staging with @moltam89 and came to the conclusion that we can't use the remote Live group's DDMStructures as scope filters on the staging side. DDMStructure must be staged if we want to use it in this scenario but with remote staging.

I used stagingGroupHelper.isLocalStagingGroup(getScopeGroupId()) for this reason.

**Comment by dacousalr** [comment]
Thanks for your prompt answer, @balazssk 

Another thing that I have detected is that a warning message appears when publishing:
`2019-02-06 11:12:43.711 WARN  [liferay/background_task-1][BaseExportImportPortletPreferencesProcessor:91] Unable to export portlet preferences value for class com.liferay.dynamic.data.mapping.model.DDMStructure with primary key 32123`

Although it does not have functional impact, would it be possible to get rid of it?

**Comment by balazssk** [comment]
I'm looking into it

**Comment by balazssk** [comment]
Hi @dacousalr ,
I'm think this part will need some changes to remove the false warning message: 
https://github.com/liferay/liferay-portal/blob/master/modules/apps/asset/asset-publisher-web/src/main/java/com/liferay/asset/publisher/web/internal/exportimport/portlet/preferences/processor/AssetPublisherExportImportPortletPreferencesProcessor.java#L385

I might need more time to test various approaches

**Comment by dacousalr** [comment]
Ok @balazssk,

I will close this PR if you don't have any objection and I will wait for a new one with the necessary remaining changes.

Best

**Pull request closed without merging**
