### PR TITLE
LPS-91369 Using author to avoid confusing author with last modifier

### PR DESCRIPTION
**Pull request by balazssk**
Hi @dacousalr ,

Based on https://issues.liferay.com/browse/PTR-657, I've opened 
https://issues.liferay.com/browse/LPS-91369 and changed User Name to Author.

Can you please review?

Thanks,

### CODE REVIEW

**Comment by balazssk** [comment]
Hi @dacousalr ,
I know you must be flooded with work, but I think this PR would be a quick-win for you.
Can you please have a look at it?

Thanks,

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/68949.

**Comment by balazssk** [comment]
Cheers @dacousalr !

**Pull request closed without merging**
