### PR TITLE
LPS-86179 Replacing deprecated AssetPublisherHelper

### PR DESCRIPTION
**Pull request by balazssk**
Hi @dacousalr ,

Rebased this fix to master from https://github.com/dacousalr/liferay-portal-ee/pull/73 after realizing it is missing from master as well, can you please review it?

Thanks,

### CODE REVIEW

**Comment by dacousalr** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by balazssk** [comment]
Just saw this during my startup of a bundle:

`2018-10-10 15:46:04.316 ERROR [main][com_liferay_asset_publisher_web:97] [com.liferay.asset.publisher.web.util.AssetRSSUtil(1139)] Field _assetPublisherHelper in component class com.liferay.asset.publisher.web.util.AssetRSSUtil must not be static`

Guess my AssetRSSUtil isn't a good solution

**Comment by dacousalr** [comment]
I am afraid not @balazssk,

According to OSGi specs:
> Only instance fields of the field types above are supported. If a referenced field is declared with the static modifier or has a type other than one of the above, SCR must log an error message with the Log Service, if present, and the field must not be modified.

**Comment by balazssk** [comment]
Morning,
Thank you for the help with OSGI.
Given the static context of AssetRSSUtil, should it be revised into an interface-Impl combo, just like AssetPublisherHelper (old one of course deprecated)? Hoping it is not called from another static context, or do you know another way to autowire assetPublisherHelper into it?

**Comment by dacousalr** [comment]
Hi @balazssk,

I have talked to @jkappler and he is going to "componentize" AssetRSSUtil in master since its only usage is from AssetPublisherPortlet.

**Comment by balazssk** [comment]
Cheers both.

**Pull request closed without merging**
