### PR TITLE
[TECHNICAL-SUPPORT] LPS-96589

### PR DESCRIPTION
**Pull request by jonathanmccann**
@dacousalr,

Thank you for the information provided on the PTR. Please let me know what you think of the solution and if you see any issues with it.

I ended up not checking for permissions in the `isMovable` method because that option is only available if the original container no longer exists so there is no clear container to check permissions against. I decided to leave the permission checking up to the popup modal that will display once LPS-97080 and LPS-97081 are resolved.

Thank you.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Thank you @jonathanmccann,

Before reviewing it more in depth, I would like to wait for LPS-97080 and LPS-97081 to be merged.

**Comment by jonathanmccann** [comment]
Ah, I didn't know those were being worked on currently. Thanks for letting me know.

**Comment by jonathanmccann** [comment]
@dacousalr I have rebased the pull and resolved the conflicts with the latest changes. Please let me know if there's anything else you need from me.

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
@dacousalr Is there any update on this review?

**Comment by dacousalr** [comment]
Hi @jonathanmccann,

I have rebased your PR in my local machine and discovered that when restoring a Web Content whose container still exists, a modal appears asking where it should be moved to.

Could you double-check it, please? After that, please resend me the resulting PR with the needed modifications if any.

Thanks

**Comment by jonathanmccann** [comment]
@dacousalr What permissions did the user have when you were testing? I just tested with the admin user and the article was restored immediately to its folder.

**Comment by dacousalr** [comment]
I have tested with the admin user, too. Could you send me this PR rebased to recheck, please?

Thanks

**Comment by jonathanmccann** [comment]
https://github.com/dacousalr/liferay-portal/pull/134

**Pull request closed without merging**
