### PR TITLE
LPS-178820 Check Site's default language before returning Exception

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hey @dacousalr ,

Could you review this pull request, please?

You can find more details about how to reproduce this issue in [LPS-178820](https://issues.liferay.com/browse/LPS-178820).

Originally I thought about introducing some change in friendly-url-taglib to consider this case, or even adding a new param to that taglib so we can pass a defaulLanguage to it, but after the conversation we both have on Slack with @robertoDiaz I decided to just check on JournalArticle whether there is an URL for Site's default language before returning an exception.

Let me know if you have any question about it.

Thanks.

Regards.

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Hi @antonio-ortega!

Sorry for the delay in my response.

The approach looks good to me. I would only like to discuss if it would be better to use LocaleUtil.getSiteDefault instead of LocaleUtil.getDefault. Would this alternative have an unintended impact on the original issue?

Best,
Daniel

**Comment by antonio-ortega** [comment]
Hi, @dacousalr,

It'd be the same for this issue. Both options would return the same language.

I was just trying to follow the same pattern defined in [friendly-url-taglib](https://github.com/liferay/liferay-portal/blob/master/modules/apps/friendly-url/friendly-url-taglib/src/main/java/com/liferay/friendly/url/taglib/servlet/taglib/InputTag.java#L210-L211) where defaultLanguageId is taken from LocaleUtil.getDefault(). 
```
String languageId = LanguageUtil.getLanguageId(
	LocaleUtil.getDefault());

return LocalizationUtil.getXml(
	HashMapBuilder.put(
		languageId, urlTitle
	).build(),
	languageId, "UrlTitle");
```

But I can understand in this case, it could make more sense to take if from language's site.

Thanks.

Regards.

**Comment by antonio-ortega** [comment]
Rebased and forced pushed with additional commit considering site's default language

**Comment by dacousalr** [comment]
Thank you for clarifying and adapting the solution, @antonio-ortega!

I will send it to the Product Team for final review.

**Comment by dacousalr** [comment]
Continue in https://github.com/liferay-echo/liferay-portal/pull/11496

**Pull request closed without merging**
