### PR TITLE
LPS-121978 Reverse Sort Direction arrows are not working "Filter and Order"

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @dacousalr 

could you please review my changes?

I added the orderByComparator paramter to the getDDMStructures method to handle the ordering if there is no search keyword.

Thanks, Roland

https://issues.liferay.com/browse/LPS-121978

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Hi @rolandpakai,

Can you resend it with the fixes in order to avoid the following message?:


> [echo] Detected build services changes. See above build services log for more
> [echo] information. Make sure to commit in all build services results.

Thanks in advance

**Comment by rolandpakai** [comment]
Resent: https://github.com/dacousalr/liferay-portal/pull/281

**Pull request closed without merging**
