### PR TITLE
LPS-114484 Order by column preference is lost in Asset Publisher after upgrade unless it is filtered by field

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi @dacousalr ,

Could you review this pull request, please?

You can find more information in [LPS-114484](https://issues.liferay.com/browse/LPS-114484).

In LPS-63404 we introduced the upgrade of this preference, OrderByColumn, but it was only considered in case the option 'Filter by Field' was enable. Per my understanding, I think we should do it always, not only when that option was selected.

The part about the regular expression is just to match the same fields name in DDMStructure, otherwise the fieldName is not found in the form, the preference not updates and the user sees how the configuration was lost.

Thanks.

Regards.

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
ci:forward

**Pull request closed without merging**
