### PR TITLE
LPS-102053

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-102053

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
ci:test:relevant

Restarting test, the previous test aborted due to test server issues.

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78937.

**Pull request closed without merging**
