### PR TITLE
LPS-110894 Giving edit permission on an individual Content Page doesn't work

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-110894](https://issues.liferay.com/browse/LPS-110894)

Hi Daniel,

I hope you can review my changes.

In short, there is a permission checking issue when editing content pages. Regular users with update permission on individual content pages are unable to access the page in edit mode. 

The root cause it that content pages has two layout records persisted: published and draft. Granting permissions happens on the published layout, so checking permission should be done on the same.

Thank you,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Hi @istvansajtos,

Could you check if your changes on Content Pages should be applied to Asset Display Page Templates as well?

Thanks in advance

**Comment by istvansajtos** [comment]
Hi @dacousalr,

Display Page Templates are also affected, but there additional (or completely different) changes will be required. As I see, we are checking for UPDATE permission on Layout while permissions were granted on LayoutPageTemplateEntry .

While I am working on this, do you think the current changes are safe to go out in an SDH?

Thank you.

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Thanks for looking into the Display Page's case, @istvansajtos 

Regarding the SDH, I am afraid that the fix should also change com.liferay.layout.content.page.editor.web.internal.display.context.ContentPageEditorDisplayContext._hasUpdateContentPermissions() and com.liferay.layout.content.page.editor.web.internal.display.context.ContentPageEditorDisplayContext._hasUpdatePermissions() to check the permission against the proper plid

Could you also review those points and resend?

Thanks in advance

**Pull request closed without merging**
