### PR TITLE
[TS] LPS-112207 iframe-web: Use escapeJS instead

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi @dacousalr ,

**Context**
The Iframe widget is currently escaping the URL incorrectly, which results in URL parameters being lost.

**Issue:** 
The **&** is being escaped to **&amp\;** when crafting the URL. Using escapeJS instead of escapeHREF resolves the issue.

If I should send this to another reviewer, please let me know.

Feel free to let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
ci:forward

**Comment by dacousalr** [comment]
ci:forward

**Comment by dacousalr** [comment]
ci:forward

**Comment by dacousalr** [comment]
ci:stop

**Comment by dacousalr** [comment]
ci:forward

**Pull request closed without merging**
