### PR TITLE
[TS] LPS-120520 Don't delete PortletPreferences on the target Layout if there is a corresponding PortletPreferences on the source Layout

### PR DESCRIPTION
**Pull request by balazssk**
Hi @dacousalr ,

`PortletPreferencesLocalService#deletePortletPreferences` has an onAfterRemove Listener `SubscriptionPortletPreferencesModelListener#onAfterRemove` which is triggered if we hard reset the target Layout's PortletPreferences to zero during Content Page Save/Publication.

Can you please review?
https://issues.liferay.com/browse/LPS-120520

Thanks,
Balázs

### CODE REVIEW

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
ci:forward

**Pull request closed without merging**
