### PR TITLE
[TS] LPS-96035 SlidingWindowSearcher is not used for searchCount() method

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-96035](https://issues.liferay.com/browse/LPS-96035)

Hi Daniel,

Please review my changes.

[LPS-74395](https://issues.liferay.com/browse/LPS-74395) solved a search permission filter performance issue, but it still persist when searchCount() is called. The reason is that the introduced SlidingWindowSearcher doesn't get activated as it depends on the *start* and *end* values which we define for *search* method, but cannot supply for *searchCount*.

Please let me know if there is anything I can help you with.

Thank you,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:search

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:search

**Comment by istvansajtos** [comment]
Hi Daniel, @dacousalr 

Please let me know if you think my changes are safe to be delivered as an SDH.

Thank you.

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/2405.

**Comment by dacousalr** [comment]
Hi @istvansajtos,

It seems safe but I would like it to be reviewed by Eudaldo first.

**Comment by istvansajtos** [comment]
Hi @dacousalr ,

I appreciate your feedback. Then I will wait for Eudaldo's update.

**Pull request closed without merging**
