### PR TITLE
LPS-128928 AssetCategory association may be lost when content editor has limited permissions

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-128928](https://issues.liferay.com/browse/LPS-128928)
Hi Daniel,

I hope you can review my changes.

In short, the issue is that AssetCategoriesSelectorTag filters the categories to display by permission. This means that if an editor doesn't have permission to see any of assigned categories, those associations are lost when the editor updates the content.

My changes ensures to send back all the assigned categoryIds to the server, even if the editor doesn't have access to those categories.

Thank you,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
@dacousalr , please let me know if you think we can give out the changes as SDH. Thank you!

**Comment by dacousalr** [comment]
Hi @istvansajtos,

Could you please take a look at the failing tests?

Thanks in advance

**Comment by istvansajtos** [comment]
Hi @dacousalr ,

I'm looking into the failures.

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
Hi @dacousalr ,

I've updated my branch, it should pass tests this time. We will see. :)

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
Hi Daniel, @dacousalr 

Please let me know if you think we can give out the fix as an SDH.

Thank you!

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/4223. [See changes here.](https://github.com/dacousalr/liferay-portal/compare/c53873e82d11~1...c53873e82d11)

**Pull request closed without merging**
