### PR TITLE
LPS-116762

### PR DESCRIPTION
**Pull request by MarcellGyopos**
Hi @dacousalr ,
Could you please review this pull request?
Thank you and best regards,
Marci

### CODE REVIEW

**Comment by MarcellGyopos** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Hi @MarcellGyopos,

There seems to be some other SF issues.

In any case, I have taken a look at the PR and the solution seems to be more related to U&SM than to WEM. So, please, fix the SF issues and send it to the US&M SME for review.

Thanks!

**Pull request closed without merging**
