### PR TITLE
[Technical Support] LPS-75041 Page permissions don't take effect in Navigation Menu portlet on the staging site after adding View Staging permission

### PR DESCRIPTION
**Pull request by zsigmondrab**
Hi Daniel,

the real problem is clarified here: https://issues.liferay.com/browse/LPS-75041?focusedCommentId=1178858&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1178858

According to my opinion, even though a staging related permission makes the behavior inconsistent, this is rather a WCM related problem and not a clear staging one.

Could you please take a look at help us with finding out if this change might cause any problem?

Thanks in advance,
Zsigmond

### CODE REVIEW

**Comment by yuhai** [comment]
ci:reopen

**Comment by yuhai** [comment]
ci:retest

**Comment by dacousalr** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/matethurzo/liferay-portal/pull/1804. [See changes here.](https://github.com/dacousalr/liferay-portal/compare/5aaed3e51df5~1...5aaed3e51df5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dacousalr** [comment]
Hi @zsigmondrab, @yuhai,

First of all, sorry for the delay in my response.

Unfortunately, this fix seems to cause a bad redirect in master when creating more than one page. No matter which you choose, it always redirects to the first one.

Taking into account this, I propose to keep the non-related Staging code to avoid this situation.

Sent to https://github.com/matethurzo/liferay-portal/pull/1804

Best Regards

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/yuhai/liferay-portal/pull/41. [See changes here.](https://github.com/dacousalr/liferay-portal/compare/5aaed3e51df5~1...5aaed3e51df5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
