### PR TITLE
LPS-107879 use freemarker taglibs inside fragment mapping

### PR DESCRIPTION
**Pull request by jgarcialr**

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Hi @jgarcialr,

I will review this a bit more in depth but you can deliver it as SDH.

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Hi again @jgarcialr,

I am afraid I cannot pass this PR since the portlet preferences generated by the embedded portlet are being saved in the the first page found not in the current one.

Could you check it, please?

Thanks in advance

**Pull request closed without merging**
