### PR TITLE
LPS-145876 Share friendly url on social bookmarks when Display page i…

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Share friendly URL on social bookmarks when Display page is available for journal articles 

cc/ @dacousalr Please review, let me know if this should go to Echo team. thanks.

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Hi @georgel-pop-lr,

I have reviewed this PR and there are some points I would like to comment about it:

1) When the social bookmarks are displayed in abstract view, blogs or documents with display page friendly URLs should be taken as the ones to share
2) If the Asset Publisher has been configured as View in Full Content, then it should only share the portlet Friendly URL
3) The fix should also be applied to portlet_display_template_rich_summary.ftl
4) Consider renaming hasFriendlyURLToShare to hasDisplayPage or creating a method called getDisplayPageFriendlyURL which return null if there is not any Display Page for that asset.
5) Fix Semantic versioning

Please, let me know if further clarifications or indications are needed.

Best,
Daniel

**Pull request closed without merging**
