### PR TITLE
LPS-114083 Take into account duplicated names in UpgradeLayoutPrototype.java

### PR DESCRIPTION
**Pull request by achaparro**
cc/ @Samziemer

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Thank you guys,

It looks good.

As we discussed in #237, could you add an extra commit to control that [the newName is equal or less than 75 characters](https://github.com/dacousalr/liferay-portal/pull/237#issuecomment-639407952) and another one to inform users that [the name will be changed](https://github.com/dacousalr/liferay-portal/pull/237#issuecomment-638875989)?

Thanks in advance

**Comment by SamZiemer** [comment]
resent here: https://github.com/achaparro/liferay-portal/pull/604

**Comment by SamZiemer** [comment]
ci:close

**Pull request closed without merging**
