### PR TITLE
[TECHNICAL SUPPORT] LPS-97281 Expire date color remaining green after 'Never Expire' checkbox ticked 

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey @dacousalr, 

[LPS-97281](https://issues.liferay.com/browse/LPS-97281),

Please review it

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
Hi @NemethNorbert,

This does not seem to be the proper fix.

This issue is reproducible with any form which contains a input date field with disabled checkbox plus the Form Validator component.

The conflict is caused by the fact that the input date field is not cleaning the success or failure CSS classes that the Form Validator component adds.

You should analyze the code of this components in order to reset those classes.

**Comment by NemethNorbert** [comment]
Hi @dacousalr,

The form validator does not listen to the disabled checkbox and from my perspective the css specificity applied to the form field causes the issue. Disabled is an attribute of the input field, and the corresponding css class should override any previous css classes that were present.
Also you are quite right about my solution does not solves the issue Portal wide. It is something that probably needs to be fixed in Clay in order to achieve that.

Thanks

**Comment by dacousalr** [comment]
I totally agree with you, @NemethNorbert 

This should be solved within FEI although this PR could be a valid SDH.

**Pull request closed without merging**
