### PR TITLE
LPS-111292 file might not exist

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/72.

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/javierdearcos/liferay-portal/pull/18.

**Pull request closed without merging**
