### PR TITLE
LPS-79521

### PR DESCRIPTION
**Pull request by brianikim**
Hello @dacousalr ,

https://issues.liferay.com/browse/LPS-79521

I am sending this PR directly to you with the changes implemented as you requested in:
https://github.com/ealonso/liferay-portal/pull/1586

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:reopen

**Comment by brianikim** [comment]
ci:retest

**Comment by brianikim** [comment]
Hello @dacousalr ,

Any updates on this PR? I would greatly appreciate it if you could review this as the customer has been waiting for about a month now for this to be resolved. Thanks.

Sincerely,
Brian Kim

**Comment by dacousalr** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/1647. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
