### PR TITLE
LPS-79748

### PR DESCRIPTION
**Pull request by SpencerWoo**
https://issues.liferay.com/browse/LPS-79748
Updated from https://github.com/ealonso/liferay-portal/pull/1615 -- changed the fix.

The issue I want to fix is where User X can't add Site A to User Y through user membership page (because filtering by roles) but User X has the permission to navigate to Site A and add User Y to membership anyways.

Let me know if there's a better way.  Membership Page assigning User Groups works as expected but assigning Sites does not.

### CODE REVIEW

**Comment by SpencerWoo** [comment]
ci:test

**Comment by dacousalr** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dacousalr** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dacousalr** [comment]
Closing this. Please see https://github.com/ealonso/liferay-portal/pull/1669

**Pull request closed without merging**
