### PR TITLE
LPS-79498 checking role for all groups when groupid is zero

### PR DESCRIPTION
**Pull request by linolaoj**
Hi @dacousalr, 
In my tests it is working as expected. This is the function that I use for test:
`JournalArticleServiceUtil.search(companyId, groupId, folderIds, classNameId,
				articleId, version, title, description, content, ddmStructureKeys, ddmTemplateKeys, displayDateGT, 
				displayDateLT, status, reviewDate, andOperator, start, end, obc);`

Please let me know if you still find any errors.
Thanks!

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
ci:test

**Comment by dacousalr** [comment]
ci:retest

**Comment by dacousalr** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/1778. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
