### PR TITLE
LPS-107879 use freemarker taglibs inside fragment mapping

### PR DESCRIPTION
**Pull request by jgarcialr**

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84606. [See changes here.](https://github.com/dacousalr/liferay-portal/compare/d0d2401d6bed~1...d0d2401d6bed)

**Pull request closed without merging**
