### PR TITLE
LPS-121251 WIP! Asset Thumbnail and icons are not working in Search Results

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-121251

Hi Dani,

See my [comment](https://issues.liferay.com/browse/PTR-2230?focusedCommentId=2369326&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2369326) on the PTR regarding the draft changes I'm sending you here.

Regards,
Tibor

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
Unrelated SF

**Comment by lipusz** [comment]
Let me take a look at the compile error. I may have pushed an older version.

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
Some functional tests may need to be adapted to the new results layout, however I didn't have the time to check if these failures are related or not.

:information_source: For Search related known CI results, please refer to [this](https://docs.google.com/spreadsheets/d/1cDzu4itg1XPtK4EyuwWB3MBwK3m7MpT3LqLcXltx9QA/edit?pli=1#gid=0) spreadsheet. This  can be accessed through https://search-ci.liferay.com/.

If you are not sure, feel free to reach out to the Search QA team in [#t-search-z-cont-integ](https://liferay.slack.com/archives/CLBEAPQ5D) or mention them through `@liferay/qa-search`.

Regards,
Tibi

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/liferay-search/liferay-portal/pull/88. [See changes here.](https://github.com/dacousalr/liferay-portal/compare/e732aa8e64d0~5...e732aa8e64d0)

**Pull request closed without merging**
