### PR TITLE
[TECHNICAL SUPPORT] LPS-159309 Widgets will show portlet configuration on content page if they are placed below a drop zone fragment

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,

When we start rendering the fragments under the masterLayout with a fragmentLayoutTag, it will set the showPortletTropper attribute to true in the request, and will remove it, once it finished rendering.
The root cause is that the dropZone fragment renders a FragmentLayoutTag as well, that will end up removing the showPortletTopper attribute from the request when finished rendering. When it is set to true, we won't render the portlet configuration, which is the expected behaviour on a content page. However the remaining widgets that we might render under a drop zone on a content page still needs this attribute in the request to not show their configuration.
 My fix restores this attribute once we finished rendering a dropZoneFragment.

Please review my change.

Thanks

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Hi @NemethNorbert,

I have not tested your PR yet, but looking at the code in https://github.com/liferay/liferay-portal/blob/aebbc0b54eef4668bfc9ca313f7b73b8e87d3cb4/modules/apps/layout/layout-taglib/src/main/resources/META-INF/resources/render_fragment_layout/page.jsp#L30-L57, would it be possible to check and set the showPortletTopper attribute there?

I am thinking of something similar to the following:
```

    Boolean showPortletTopper = (Boolean) request.getAttribute(WebKeys.SHOW_PORTLET_TOPPER);

    try {
		request.setAttribute(WebKeys.SHOW_PORTLET_TOPPER, Boolean.TRUE);

	...

	}
	finally {
		if (!showPortletTopper) {
			request.removeAttribute(WebKeys.SHOW_PORTLET_TOPPER);
		}
	}
```

What do you think?

**Comment by NemethNorbert** [comment]
> Hi @NemethNorbert,
> 
> I have not tested your PR yet, but looking at the code in https://github.com/liferay/liferay-portal/blob/aebbc0b54eef4668bfc9ca313f7b73b8e87d3cb4/modules/apps/layout/layout-taglib/src/main/resources/META-INF/resources/render_fragment_layout/page.jsp#L30-L57, would it be possible to check and set the showPortletTopper attribute there?
> 
> I am thinking of something similar to the following:
> 
> ```
> 
>     Boolean showPortletTopper = (Boolean) request.getAttribute(WebKeys.SHOW_PORTLET_TOPPER);
> 
>     try {
> 		request.setAttribute(WebKeys.SHOW_PORTLET_TOPPER, Boolean.TRUE);
> 
> 	...
> 
> 	}
> 	finally {
> 		if (showPortletTopper == null || !showPortletTopper) {
> 			request.removeAttribute(WebKeys.SHOW_PORTLET_TOPPER);
> 		}
> 	}
> ```
> 
> What do you think?

I started to explore that possibility as well, however showPortletTopper is true when we first arrive in the finally statement, so that code would never run I believe. In case we leave showPortletTopper true in the request, the masterPage with the menuPortlet and the searchbar won't show its portletConfiguration.

I also think the problem is caused by the drop zone fragment when it renders the fragmentLayoutTag. I figured its best to just regent the attribute, as it will be cleared up anyway by renderFragmentLayout Finally statement, once its finished rendering all the fragment, including the nested dropzoneFragments.

Thanks,

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/9237. [See changes here.](https://github.com/dacousalr/liferay-portal/compare/3f034bed377f~1...3f034bed377f)

**Pull request closed without merging**
