### PR TITLE
LPS-114135 Can't delete line-breaks in fragments with one keystroke

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,

[LPS-114135](https://issues.liferay.com/browse/LPS-114135)
I don't know what was the original reasoning behind not delegating the key events when the editor is active, but in my tests I did not find any regression.

Pls review the changes.

Thank you,

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/739.

**Pull request closed without merging**
