### PR TITLE
LPS-105108 Set the parameter if present

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
Hey @dacousalr

What is the status of this PR??

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81556.

**Pull request closed without merging**
