### PR TITLE
LPS-86179 Use the service. In this way we avoid duplicate code and have backwards compatibility

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/64150. [See changes here.](https://github.com/dacousalr/liferay-portal/compare/0e4f93ba57c1~1...0e4f93ba57c1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
