### PR TITLE
[TS] LPS-141133 In Web Content, folder and search are not restored when structure filter is removed

### PR DESCRIPTION
**Pull request by joseluisbango**
Hi @dacousalr,

We need to remove 'ddmStructureKey' from the URL when the user removes it from the filter in order to perform the new search.

See [LPS-141133](https://issues.liferay.com/browse/LPS-141133).

Please let me know if you have any questions.

### CODE REVIEW

**Comment by joseluisbango** [comment]
ci:test

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
ci:forward

**Pull request closed without merging**
