### PR TITLE
LPS-108211 Do not restrict to layouts with classNameId being 0

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @dacousalr 

I added a commit that removed the condition that classNameId has to be 0 as there may be Layouts needed to be represented on the sitemap whose classNameId might not be 0.

However, an interesting thing is that when a Display Page Template is created, two Layouts with asset_display type are created in the database:

1. a Layout with classNameId 0 and with status 2 (draft)
2. a Layout with a classNameId corresponding to com.liferay.portal.kernel.model.Layout and status 0 (published)

Is this an intended behavior?

Thank you and best regards,
István

### CODE REVIEW

**Comment by dacousalr** [comment]
Hi @IstvanD,

Yes, it is the intended behavior so I do not see the need for this change.

Best

**Comment by IstvanD** [comment]
Hi @dacousalr 

Thank you for the clarification.

My changes don't affect how many Layouts are created but which Layouts get fetched by `getAllLayouts`. 

By examining a customer's database who reported this issue, I realized that Layouts with classNameId =/= 0 has to be included in the sitemap as well.

Therefore, the changes I made in the last commit may be needed after all.

Please let me know what you think.

Thank you and best regards,
István

**Comment by dacousalr** [comment]
Thank you for the clarifications, @IstvanD,

I still think this change is not needed because, firstly, having two layout entries is something in common with Content Pages as well, and secondly, only one of these two layout entries represents the page to be shown (classNameId == 0), the other one is for being edited and keeping unpublished changes (classNameId =/= 0), which would not be relevant for this case.

What do you think, @jkappler?

**Comment by IstvanD** [comment]
Hi @dacousalr 

I see. In the case I mentioned earlier, the db had only entries for content page layouts where classnameId =/= 0.
Could it be that they were created prior to the two-layout functionality being introduced or it might be some idiosyncratic case due to customization?

**Comment by jkappler** [comment]
Hi @IstvanD, classNameId different than 0 is for drafts. So, the relevant ones are with classname == 0 (and aren't of type asset_display)

**Comment by jkappler** [comment]
Don't pay attention to my previous message @IstvanD. I agree with @dacousalr. Still, it's weird what you saw in the customer db

**Comment by jkappler** [comment]
ClassNameId not equal to 0 is used mainly for draft layouts, the published one will have a 0 as value

**Comment by IstvanD** [comment]
@dacousalr , @jkappler thank you for your answers.
I observed that for content pages both the 0 and non-0 classNameId layouts will have the status 0.
And for asset_display layouts, it's the one with the 0 classNameId that has status 2 (draft), while the one with the non-0 classNameId has status 0.

**Comment by dacousalr** [comment]
Hi @IstvanD,

> And for asset_display layouts, it's the one with the 0 classNameId that has status 2 (draft), while the one with the non-0 classNameId has status 0.

Yes, there seems to be a lack of synchronization between the status values. In fact, real status value is stored in the LayoutPageTemplateEntry related to that AssetDisplay Layout entry.

I think that the team could take a look at the status values to be more consistente but in any case, real layouts, those that are taken into account at the time of rendering the page served when accessing via display friendly url, have their classNameids set to 0.

**Comment by IstvanD** [comment]
@dacousalr OK. Meanwhile, I asked the customer how they created those Layouts, hoping that may figure out a solution for their special case.

**Comment by IstvanD** [comment]
Hi @dacousalr , @jkappler 

With the help of the customer, I could finally reproduce the case when a published Layout is created whose classNameId != 0.

1. create a new page template collection in site builder
2. create a new content page template in that collection
3. create a new content page from that page template

Result: two entries in the Layout table will be created for the content page in step 3.
1. one with a classNameId belonging to com.liferay.layout.page.template.model.LayoutPageTemplateEntry, the "published" page
2. one with a classNameId belonging to com.liferay.layout.page.template.model.Layout, the "draft" page

The first page is supposed to appear in the sitemap, but it won't due to it's classNameId !=0.

Please let me know, that in light of this, should I modify the solution.

Thank you and best regards,
István

**Comment by dacousalr** [comment]
Thank your for your research, @IstvanD,

Then, yes, the solution has to be changed to also include them but keeping the "draft" layouts out.

**Pull request closed without merging**
