### PR TITLE
LPS-106908 We need the instanceId in non instanceable widgets because of personalization, so treat it like we do when adding the widgets through d&d. RuntimeTag handles instanceId with values 0

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
@ealonso

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/liferay/liferay-portal/pull/3700.

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84059.

**Pull request closed without merging**
