### PR TITLE
LPS-135170 Add content page portlets to the portlets list

### PR DESCRIPTION
**Pull request by holatuwol**
Sending just the one commit from https://github.com/dacousalr/liferay-portal/pull/338

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant:norebase

**Comment by holatuwol** [comment]
ci:stop

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
hey @dacousalr ,

I am re-running the test to confirm, but the results look good. Please proceed with this PR as soon as possible.

**Comment by brianikim** [comment]
@holatuwol , this PR can be closed. sending directly to liferay-echo

**Comment by brianikim** [comment]
https://github.com/liferay-echo/liferay-portal/pull/6321

**Pull request closed without merging**
