### PR TITLE
LPS-79988 While checking new Notifications IllegalArgumentException is thrown, page crashes and dockbar disappears.

### PR DESCRIPTION
**Pull request by moltam89**

### CODE REVIEW

**Comment by moltam89** [comment]
ci:test

**Comment by moltam89** [comment]
ci:retest

**Comment by moltam89** [comment]
Hi @dacousalr ,

I don't think that the failing tests are related to the current fix.
Could you please check this pr?

Thanks,
Tamás

**Comment by dacousalr** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dacousalr** [comment]
Hi @moltam89,

The root cause is that the entryURL populated by JournalArticleLocalServiceImpl.getURLViewInContext is generated without domain. Although your commits are necessary, that entryURL should be complete, that is, it should start by http:// or https://
In addition to this, an upgrade step should be implemented to transform the incorrectly generated relative URLs to complete URLs in the column payload of the table UserNotificationEvent.
Could you review these points?

**Comment by moltam89** [comment]
Hi @dacousalr ,

actually it isn't the JournalArticleLocalServiceImpl.getURLViewInContext method which generates the entryURL in the current use case.
After taking a deeper look on this issue, it's not clear for me what is the expected behavior anymore. Let me summarize what I found so far.

Before [LPS-76339](https://issues.liferay.com/browse/LPS-76339), we always generated links which pointed to the Control Panel. 

LPS-76339 changed this behavior for articles where the display page is set, so there is an Asset Publisher on a page which can display the article.

[LPS-77464](https://issues.liferay.com/browse/LPS-77464) extended this fix, the JournalArticleLocalServiceImpl.getURLViewInContext method is also used for articles where the display page is not set.
This works fine, until the article is displayed in a Web Content display.

My question is, what should happen if the display page is not set, and the article isn't displayed in a Web Content Display portlet either?
Should the links point to the Control Panel? Do we want to add permission checks, to see if the user actually has access to it?

**Note:**
I have another [pull request](https://github.com/moltam89/liferay-portal/pull/421) which deals with a very similar issue. It's about the Activities portlet, which currently generates links only if the display page is set for the article. 
Is my assumption correct, that the link generation for the two portlets should be the same?

Let me know if I should create an SME request instead of communicating on this pull request.
I'm getting a bit confused about what we should handle as a bug.

Thanks,
Tamás

**Comment by dacousalr** [comment]
Thank you for your clarifications, @moltam89,

In any case, urls persisted in database should start with http:// or https:// regardless of existing an AP or WCD or none of them.

As it seems there are some issues involved, please open an SME Request.

Thanks!

**Comment by moltam89** [comment]
Hi @dacousalr ,

I opened an SME request.

Thanks,
Tamás

**Pull request closed without merging**
