### PR TITLE
LPS-1122095 Check collisions and generate a new FriendlyURL if necessary

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/dacousalr/liferay-portal/pull/282.

**Comment by dacousalr** [comment]
Fixed commit prefixes from LPS-1122095 to LPS-122095

**Pull request closed without merging**
