### PR TITLE
[TS] LPS-122314 Upgrade step for LayoutPageTemplateEntry permissions

### PR DESCRIPTION
**Pull request by vendeltoreki**
Hi @dacousalr ,

As discussed on [PTR-2111](https://issues.liferay.com/browse/PTR-2111), I've added dummy upgrade steps:
* "3.1.2" to "3.1.3" for 7.2.x backport
* "1.1.1" to "1.1.2" for 7.1.x backport
* Increased the version of step 3.1.3 to 3.1.4

The https://github.com/dacousalr/liferay-portal/commit/992c63de2883ecc5e12a0d8e5e915722caff456c commit makes the upgrade step idempotent: it will not change anything if executed twice.

Please review my changes.

Thanks,
Vendel

### CODE REVIEW

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Hi @vendeltoreki,

I have tested it by upgrading from 6.2 and setting view permissions on some Global Page Templates for Test Role but, although the permissions are copied, the user is still unable to choose any of the upgraded page templates to create a new page based off of them.

Could you please specify which permissions you are setting for each Global Page Template and Test Role?

Thanks in advance

**Comment by vendeltoreki** [comment]
Hi @dacousalr ,

I've added the following roles in 6.2:

Page Templates: Access in Control Panel
Page Templates: Configuration
Page Templates: Permissions
Page Templates: Preferences
Page Templates: View
Page Templates > Page Template: Delete
Page Templates > Page Template: Permissions
Page Templates > Page Template: Update
Page Templates > Page Template: View
Portal: Go to Control Panel

I was experimenting with another fix in the past: https://github.com/vendeltoreki/liferay-portal/compare/master...vendeltoreki:LPS-122314-fix
This one copied the portlet related permissions as well (`com_liferay_layout_prototype_web_portlet_LayoutPrototypePortlet` ==> `com_liferay_layout_page_template_admin_web_portlet_LayoutPageTemplatesPortlet`).
During testing, I found that these are not required to actually grant permissions for the user to create pages from templates.
However, these seemed to be required to actually manage the templates.

Thanks,
Vendel

**Comment by vendeltoreki** [comment]
Well.. it seems like `Page Templates > Page Template: View` is enough in 6.2 for users to create pages from global templates. I've just created a regular role with only this permission and it worked. I guess that somewhat changes the scenario.

**Comment by dacousalr** [comment]
Hi @vendeltoreki,

Sorry for the lack of updates. Due to other tasks my bandwidth has been limited this week.

I hope to have a review next Tuesday since I will be on PTO on Monday.

**Comment by vendeltoreki** [comment]
Hi @dacousalr ,

No problem, I will resolve the conflict in the meantime.

**Comment by vendeltoreki** [comment]
Hi @dacousalr ,

To make sure we're fixing the right thing, I did some additional testing:
* In 6.2 and 7.0, a Regular Role with Control Panel > Sites > Page Templates > Resource Permissions > View role is required for the Site Administrator to be able to create pages from the page templates.
* In 7.1, an extra role is required with "Pages > Layout Page Template Entry: View", "Pages > Page Template: View", "Pages > Page Templates: View"
* In 7.2, 7.3 and master, Site administrator role is enough to do the same thing. No need for extra roles.

There's difference in resource permission of individual templates coming from upgraded env and newly created ones, they might not be the main difference. It's also possible, that the Site Admin roles also have to be changed when upgrading to different versions.

Regards,
Vendel

**Comment by dacousalr** [comment]
Thanks for sharing these results, @vendeltoreki!

The difference between 7.1 and 7.2/7.3/Master can be explained by https://issues.liferay.com/browse/LPS-92828

**Comment by SamZiemer** [comment]
Hi @dacousalr  and @vendeltoreki, 

The Upgrade team is currently going over our LPS queue and wanted to check if this ticket is still something that needs to be addressed, if so what is the current status of this review, and the ticket in general?

Thanks,
Sam Ziemer.

**Comment by vendeltoreki** [comment]
Hi @SamZiemer ,

As I remember, this code doesn't completely fix the issue, which seems to be more complicated than I first thought. This is still on my TODO list. Unfortunately, I did not have enough time to work on it. Also, there's a straightforward workaround: add some permissions manually to the role after the upgrade.

**Comment by SamZiemer** [comment]
Hi @vendeltoreki, thank you for the update, we appreciate your work on this issue!

**Pull request closed without merging**
