### PR TITLE
[TS] LPS-92704

### PR DESCRIPTION
**Pull request by balazssk**
Hi @dacousalr 

Based on your comment on https://github.com/dacousalr/liferay-portal/pull/183 I've revisited the service calls and redone it from scratch. Moved all service calls to remote services so that we can make use of the filter* calls in the persistence layer. Also added the missing type parameter you spotted.

Can you please review?
https://issues.liferay.com/browse/LPS-92704

Thanks,
Balázs

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Thanks @balazssk,

I am going to review this PR but I am afraid that is going to collide with #186

**Comment by balazssk** [comment]
Sorry, forgot I left this open, I'm working on rebasing this.

**Pull request closed without merging**
