### PR TITLE
[TS] LPS-92704

### PR DESCRIPTION
**Pull request by balazssk**
Hi @dacousalr ,

I've separated the creation logic for a sitemap and a sitemapindex branch for better readability.

As we discussed, we aim to limit the output xml to have a maximum of 50k entries or 50MB of size, whichever is reached first. With the added extra that this search is a moving window , which will only show the last limited part of the result set, having the newest ones on the end.

Sitemapindex creation can easily reach 50k entries before 50MB of size, but the sitemap path reaches the size constraint first Needed to adjust the size calculation as the final document.asXML() call will remove various xsd references from the individual entries. (Realised this when the result only had ~22k entries and 37MB in size, with this adjustment the result reached 48.9MB in my test)

While the sitemapindex scenario can be verified with the groovy script on the LPS ticket, for the sitemap scenario, we need to create JournalArticles and set them to be displayed on a target page to reach one of the limitations.

Can you please review?
https://issues.liferay.com/browse/LPS-92704

Thanks,
Balázs

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Hi @balazssk,

I have taken a first look at it and it looks good although there would be other approaches.

Have you considered to create a new service method to retrieve the newest layouts first? Maybe we could also pass all the sitemapable layout types to that new method and save some calls.

**Comment by balazssk** [comment]
That sound like it is worth a shot, I'll look into it hopefully tomorrow

**Comment by dacousalr** [comment]
Closing temporarily while investigating an alternative.

**Pull request closed without merging**
