### PR TITLE
[TS] LPS-139647 Add upgrade process for deleting wrongly created Layout and LayoutPageTemplateStructures

### PR DESCRIPTION
**Pull request by markgulacsy**
Hi @dacousalr,
This is a follow-up PR for https://github.com/dacousalr/liferay-portal/pull/349
I addressed your concerns in [this comment ](https://github.com/dacousalr/liferay-portal/pull/349#issuecomment-1161441350).
1. I made the oracleDB variable a local variable.
2. And I am deleting the rels before the layoutpagetemplatestructures.

Could you review my changes and the whole PR again, please?
Thank you in advance!

### CODE REVIEW

**Comment by markgulacsy** [comment]
ci:test:relevant

**Comment by markgulacsy** [comment]
Hi @dacousalr,
I am just wondering if you had a chance to look into this?
Thanks!

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by markgulacsy** [comment]
Hi @dacousalr,
I am just wondering if you had a chance to finish reviewing this?
Thank you!

**Comment by dacousalr** [comment]
Hi @markgulacsy,

Sorry for the delay in my update.

I will try to finish this review and push this forward next week.

**Comment by markgulacsy** [comment]
Hi @dacousalr,
No problem at all. Thank you!

**Comment by markgulacsy** [comment]
Hi @dacousalr,
Do you have any updates regarding the review of this PR?
Thanks in advance!

**Comment by dacousalr** [comment]
Hi @markgulacsy,

This PR looks good to me from the code's point of view. However, I would like to do some more testing before pushing it forward.

**Comment by markgulacsy** [comment]
Hi @dacousalr,

Thank you for the update and your work! Please let me know if there is anything I should fix or reconsider regarding this.
Thanks again!

**Comment by markgulacsy** [comment]
Hi @dacousalr,
Do you have any updates regarding the testing of this change?
Thank you!

**Comment by markgulacsy** [comment]
Hi @dacousalr,
Do you have some updates regarding this PR? Any approx. timeline maybe?
Thanks!

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/9688. [See changes here.](https://github.com/dacousalr/liferay-portal/compare/a6185c5dfabf~1...a6185c5dfabf)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/9690. [See changes here.](https://github.com/dacousalr/liferay-portal/compare/c0c6dded5d78~1...c0c6dded5d78)

**Pull request closed without merging**
