### PR TITLE
LPS-91709 Do not ignore the hidden attribute in all the cases when the layout is null

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/7460.

**Pull request closed without merging**
