### PR TITLE
[TECHNICAL SUPPORT] LPS-133735 Prevent the Page Tree and the Site Builder's Pages menu (displaying the Miller columns) from being open at the same time

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,
[LPS-133735](https://issues.liferay.com/browse/LPS-133735),
[PTR-2458](https://issues.liferay.com/browse/PTR-2458),

Based on the above linked PTR I created this solution, please review it.

Thank you,

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
Can you check the SF error please? It runs without error locally and not sure what the prettier has problem with

**Comment by dacousalr** [comment]
Hi @NemethNorbert,

Finally I could not spend time in this review this week.

Next week I will be on PTO. If a review is needed before I come back (July 12th) then feel free to send the PR to the Product Team directly to get some quicker feedback.

Best,
Daniel

**Comment by NemethNorbert** [comment]
https://github.com/liferay-echo/liferay-portal/pull/5071

**Pull request closed without merging**
