### PR TITLE
[TS] LPS-92704

### PR DESCRIPTION
**Pull request by balazssk**
Hi @dacousalr ,

I've updated the fix based on your feedback on https://github.com/dacousalr/liferay-portal/pull/176

> create a new service method to retrieve the newest layouts first

Although not exactly the same, as I opted for the general start-end range query instead of creating something like get newest X number of layouts.

Can you please review?
https://issues.liferay.com/browse/LPS-92704

Thanks,
Balázs

### CODE REVIEW

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
ci:stop

**Comment by balazssk** [comment]
Fixing SF errors and will resend

**Pull request closed without merging**
