### PR TITLE
LPS-136108 Integration Test

### PR DESCRIPTION
**Pull request by mbowerman**
Hi @dacousalr,

I made the changes that @brianchandotcom asked for in https://github.com/brianchandotcom/liferay-portal/pull/106042#issuecomment-904552790

There was one instance of a `urlToExport` that I couldn't inline because it was used in multiple places. This occurred in the `testExternalURLNotModified` method, because that URL isn't tied to anything external like a Layout or Group, so it needs its own variable. During the rename, I renamed it to "`exportedURL`" to match the format of the "`importedURL`" variable. Let me know if you disagree.

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
ci:forward

**Pull request closed without merging**
