### PR TITLE
LPS-108211 Web content articles not in sitemap.xml

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @dacousalr 

Thank you for the suggestion to test the fix with `xml.sitemap.index.enabled=false`
It didn't cover that case, but I made a modification in the last commit that handles this.

Now the articles are displayed with and without sitemap indexing.

Thank you and best regards,
István

### CODE REVIEW

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by IstvanD** [comment]
Hi @dacousalr 

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/jkappler/liferay-portal/pull/698. [See changes here.](https://github.com/dacousalr/liferay-portal/compare/790aca90a9ae~3...790aca90a9ae)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/jkappler/liferay-portal/pull/700. [See changes here.](https://github.com/dacousalr/liferay-portal/compare/d0bff30a6a92~4...d0bff30a6a92)

**Pull request closed without merging**
