### PR TITLE
LPS-79498 checking role for all groups when groupid is zero

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test

**Comment by linolaoj** [comment]
ci:reopen

**Comment by dacousalr** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dacousalr** [comment]
Hi @linolaoj,

It seems that for a guest user is returning both Web Contents. Could you re-check it, please?

Thanks!

**Comment by linolaoj** [comment]
https://github.com/dacousalr/liferay-portal/pull/46

**Pull request closed without merging**
