### PR TITLE
Lps 109019

### PR DESCRIPTION
**Pull request by balazssk**
Hi @dacousalr ,

I've made a change to the tests somewhat unrelated to this fix in https://github.com/dacousalr/liferay-portal/commit/818edb6216ce03f5a7105c3cdb59468b1a1f7c96 hope it's ok.

Can you please review?
https://issues.liferay.com/browse/LPS-109019

Thanks,
Balázs

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
Sorry about the SF error, was only focusing on the test file and forgot to double-check UpdateLanguageAction.
I'll resend the PR in a minute

**Comment by balazssk** [comment]
ci:close

**Pull request closed without merging**
