### PR TITLE
LPS-96554 checking layout view permission

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Hi @linolaoj,

Please, add a new method with parameters groupId, isPrivate and type to LayoutService and use it.

**Comment by linolaoj** [comment]
Here it is https://github.com/dacousalr/liferay-portal/pull/126
Thanks!

**Pull request closed without merging**
