### PR TITLE
LPS-121011 Customize the message to provide more info

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
Hey @dacousalr 

I change the value of the message.

I also change it in layout_action.jsp but I didn't find how to test it ;) Do we use this jsp in the portal??

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/2409. [See changes here.](https://github.com/dacousalr/liferay-portal/compare/677c82186869~3...677c82186869)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/2444. [See changes here.](https://github.com/dacousalr/liferay-portal/compare/a5b6efaa9741~4...a5b6efaa9741)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/2452. [See changes here.](https://github.com/dacousalr/liferay-portal/compare/803311fde3c0~5...803311fde3c0)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/2454. [See changes here.](https://github.com/dacousalr/liferay-portal/compare/47aae9846706~5...47aae9846706)

**Pull request closed without merging**
