### PR TITLE
LPS-127057 Ensure that a ServiceContext instance is present before calling updateFriendlyURLs method

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by laszlopap** [comment]
ci:test:relevant

**Comment by laszlopap** [comment]
ci:test:relevant

**Comment by laszlopap** [comment]
I think the test failures are unrelated. Could you please check this @dacousalr ?

Thanks!

**Comment by laszlopap** [comment]
Could you please review this @dacousalr ?
Thanks!

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/4926. [See changes here.](https://github.com/dacousalr/liferay-portal/compare/f8d483fbeb8d~1...f8d483fbeb8d)

**Pull request closed without merging**
