### PR TITLE
[TS] LPS-100142 Change from 70/30 split to 50/50

### PR DESCRIPTION
**Pull request by balazssk**
Hi @dacousalr ,

Found that this upgrade step should use 1_2_1_columns_i as it is the previously used 50/50 split for the 2nd row portlets. 1_2_1_columns_ii uses a 70/30 split.

Can you please review?
https://issues.liferay.com/browse/LPS-100142

Thanks,
Balázs

### CODE REVIEW

**Comment by balazssk** [comment]
Hi @dacousalr ,

As discussed with @achaparro in https://issues.liferay.com/browse/LPS-95219?focusedCommentId=1934702&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1934702 I've added line ending to make sure the matching is exact.

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77329.

**Pull request closed without merging**
