### PR TITLE
LPS-109848 build.gradle

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/2865. [See changes here.](https://github.com/dacousalr/liferay-portal/compare/8e757092aee0~3...8e757092aee0)

**Pull request closed without merging**
