### PR TITLE
LPS-106477

### PR DESCRIPTION
**Pull request by ricardocousolr**
Hi @dacousalr, 

This issue was reported by a customer. The solution is based on splitting the old variable `queryString` into two variables, one that includes the part of the url containing the friendly-url separator (`/-/`), and the other containing anything after the question-mark character (`?`) if present. (With this change, `queryString` respects the semantics of the HTTP standard.) 

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by ricardocousolr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82946.

**Pull request closed without merging**
