### PR TITLE
[TS] LPS-95585 Disabling asset section on page templates

### PR DESCRIPTION
**Pull request by balazssk**
Hi @dacousalr ,

I'm not really satisfied with this solution, but couldn't think of a better one.
Changing when the whole "Setup" tab appears can affect other portlets that have valid preferences on page templates.
Disabling the selector button would just cause confusion without this warning message and by completely removing the content selector we can better communicate that it is not allowed

What do you think?

https://issues.liferay.com/browse/LPS-95585

Thanks,

### CODE REVIEW

**Comment by dacousalr** [comment]
Hi @balazssk,

I think that disabling this for all cases would be too restrictive. For example, assets from Global should be selectable at least.

What do you think?

**Comment by balazssk** [comment]
Hi @dacousalr ,
I'm not 100% sure. After we discussed that WCD should never have asset addition available on page templates (https://issues.liferay.com/browse/PTR-892) and rereading the documentation I couldn't find any mentions of Global assets being includable.
I was under the impression that this would fall under the 

> you can’t directly add content, and some configuration and display options are disabled

rule.

Of course, if global assets should be available here I'll need to rethink this.

**Comment by dacousalr** [comment]
Hi @balazssk,

I cannot reproduce this issue in Master/7.1.x since Widget Page Templates are scoped to a Site.

Regarding 7.0.x, Widget Page Templates (or simply Page Templates) are scoped to a company, so the only contents that could be configured would be those from the Global Site.

Would this make sense?

**Comment by balazssk** [comment]
Hi @dacousalr ,
I can reproduce the NullPointerError on Master when the "Scope" tab is not set to Global

**Comment by dacousalr** [comment]
Hi @balazssk,

Unfortunately, I am not able to reproduce it. Could you enumerate the steps?

**Comment by balazssk** [comment]
Of course:

1. Create a new Site and add a Page Template to it
2. Place a Web Content Display Portlet on the new Page Template
3. Open the Configuration Menu of the WCD Portlet
4. Select the Setup tab and Click Select

NullPointerException is thrown in the logs, error message is displayed in the popup.

**Comment by balazssk** [comment]
I've also created an alternative solution: https://github.com/dacousalr/liferay-portal/pull/120

**Comment by dacousalr** [comment]
Hi @balazssk,

I will take a look at #120. However, I still cannot reproduce it either via Widget Page Template inside a regular site or via Global Widget Page Template inside the Global site with commit https://github.com/liferay/liferay-portal/commit/ce4f1a8dd8512fb143a3d47659f65873e5e88993

**Comment by balazssk** [comment]
I've started a bundle on that hash and I can still reproduce the issue.
Basically, you can bring up the asset selector and possibly select an asset?

**Comment by dacousalr** [comment]
I am afraid so, @balazssk,

Peek 2019-05-23 11-50

**Comment by balazssk** [comment]
Closing as Global content should be available on page templates.

**Pull request closed without merging**
