### PR TITLE
LPS-88316 Allow pending articles to be returned if no approved ones exist. Otherwise attempting to use the View in Context link for pending content will not work

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by dacousalr** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dacousalr** [comment]
Closing. See JIRA comments for more information.

**Comment by Alec-Shay** [comment]
Hello @dacousalr,

I am currently reviewing changes to the fix to address your concerns, we may need to rewrite it a bit. However, we wanted to press just to be sure -- is this something we for sure want to fix? We have had some conflicting information on this in the past (see [LPS-75533](https://issues.liferay.com/browse/LPS-75533)), which at first seemed like we may not be able to fix, although it was fixed later.

Since we are being pressured to provide a solution but are not sure this is something we will support in the long term, we just want to make sure that this is something we can commit to fixing in some form or other before we do so. If you can confirm whether this is the case, that would help us a lot in making that decision. Thank you!

**Comment by Alec-Shay** [comment]
Resent at: https://github.com/dacousalr/liferay-portal/pull/84

**Pull request closed without merging**
