### PR TITLE
LPS-96589

### PR DESCRIPTION
**Pull request by jonathanmccann**
@dacousalr 

Thanks for looking over the previous pull. I have added https://github.com/dacousalr/liferay-portal/commit/d22093a32d049fa3cc0d255e8eb46a74db8963a0 and https://github.com/dacousalr/liferay-portal/commit/27d3422610e87e67ac5052e57539d2e5ab4a1d19 to make sure that the parent container does not exist or resides in the trash in order to display the "move" option.

Please let me know if you see any other issues with the fix. Thank you.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/2445.

**Pull request closed without merging**
