### PR TITLE
[TS] LPS-110894 Giving edit permission on an individual Content Page doesn't work

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-110894](https://issues.liferay.com/browse/LPS-110894)

Hi @Daniel,

This is the continuation of https://github.com/dacousalr/liferay-portal/pull/220

Eventually, I had to change permission checking at many places to make sure both rendering and editing works well for Content Pages and Display Page Templates.

Please let me know if you miss anything or have any concern.

Thank you,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
I'm going to address the SF problems soon. Sorry for them.

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
Hi @dacousalr ,

Please let me know if you think the fix can go out in an SDH.

Thank you.

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Hi @istvansajtos,

First of all, good job for detecting those cases.

However, I have got a 404 when trying to edit a Content Page Template with the regular user.

Could you review this point, please?

If you need more details, please, let me know.

Thanks in advance

**Comment by istvansajtos** [comment]
Hi @dacousalr ,

Could you please share the steps to reproduce the mentioned 404 error? When I try to edit a Content Page Template with a regular user (with no permissions), then I get HTTP 403 Forbidden which is the expected result.

Thank you.

**Comment by dacousalr** [comment]
Hi @istvansajtos,

Re-reading my previous comment, I think I have not been clear at all. Sorry.

When I wrote regular user, I was referring to the regular user with the test role and permissions to edit that Content Page Template.

**Comment by istvansajtos** [comment]
Hi @dacousalr ,

Thanks for the clarification. Basically, you are facing the HTTP 404 error when simply going through the reproduction steps on LPS-110894, for which case I get HTTP 200 status. (But let me know if your case is different.)

That is strange, because I tested the changes for those steps before sending the PR. Moreover, after your comment yesterday I rebased to fresh master, but I still don't see the 404 problem.

Based on this, I don't think the error is related to my changes. Could you please test again after rebasing to fresh master? Maybe it is browser or other environment specific problem, but most probably it is just coming from a wrong master state. 

Thank you.

**Comment by dacousalr** [comment]
Ok, @istvansajtos,

I will do asap.

**Comment by dacousalr** [comment]
Hi @istvansajtos,

In order to be on the same page, my steps are the following:

1. Create a new user and a test role, then assign this role to the user
2. Add this user to the default site (This steps should not be needed but it will throw an error in step 7 otherwise, maybe this is another different bug)
3. Create a test Content Page Template (you will have to create a collection first)
4. Go to Site Builder > Pages and click on the Permissions of the previously created test Content Page Template
5. Assign all permissions to the created test role, just as many the default Admin user has
6. Login with the created user and edit the test Content Page Template in Site Builder > Page Templates > Page Templates

Actual result: 403 Forbidden - You do not have permission to access the requested resource.

This subcase could be fixed in a very similar way to how you fix the subcase of Display Page Templates by checking the permissions on the related LayoutPageTemplateEntry

**Comment by istvansajtos** [comment]
Many thanks for the details @dacousalr. I am going to fix that case as well.

**Comment by istvansajtos** [comment]
Hi @dacousalr ,

While I am working to fix the case you described [here](https://github.com/dacousalr/liferay-portal/pull/224#issuecomment-631495032), can you judge if the commits above are safe to go out in an SDH? Basically, I am changing only the way we check permission, but I don't modify how permissions are persisted.

I am asking about the SDH because there is some pressure from the customer.

Thank you,
Istvan

**Comment by dacousalr** [comment]
Hi @istvansajtos,

The SDH would be safe to deliver for the cases covered by this PR.

Best,
Daniel

**Pull request closed without merging**
