### PR TITLE
[TS] LSP-121651

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @dacousalr

could you please check my fix?

More details here: https://issues.liferay.com/browse/PTR-1968

Thanks, Roland

https://issues.liferay.com/browse/LPS-121651

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Hi @rolandpakai,

Tomorrow I will be on PTO and next Monday is a non-working day in Madrid so I won't be able to start my review until next Tuesday or Wednesday. If you need that this review goes faster, you can send it to the Product Team directly (Github user liferay-echo).

Best,
Daniel

**Comment by rolandpakai** [comment]
Thank you @dacousalr for letting me known.
Created new PR here: https://github.com/liferay-echo/liferay-portal/pull/2763

**Pull request closed without merging**
