### PR TITLE
LPS-80305 Shorten Description in Web Content Display

### PR DESCRIPTION
**Pull request by brianikim**
Hello @dacousalr ,

I am sending you this PR directly along with https://github.com/dacousalr/liferay-portal/pull/37.

You have requested that the change in JournalArticleAssetRenderer be its own PR as requested here https://github.com/ealonso/liferay-portal/pull/1586. 
The LPS can be found here: https://issues.liferay.com/browse/LPS-80305.

Although I made the max number of chars to 100 due to all the precedents available in the source code,
I do believe 75 is the right length in terms of UI presentation.

Let me know what you think regarding the changes. Thanks.

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test

**Comment by dacousalr** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dacousalr** [comment]
Hi @brianikim, why do you use HtmlUtil.extractText instead of HtmlUtil.stripHtml?

**Comment by brianikim** [comment]
Hello @dacousalr ,

I was following the precedents set in other parts of Liferay in which extractText was being used. Did you want me to resend with HtmlUtil.stripHtml?

**Comment by dacousalr** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dacousalr** [comment]
Hi @brianikim,

I have checked Master@b6d2486ba477bacdadc497fa2ebe64a3548f2624 and I cannot reproduce this issue either in Firefox or in Chrome. The CSS class "truncate-text" prevents content from being displayed out of bounds. 
So I will close LPS-80305 but feel free to reopen it if you can reproduce it somehow.

Best,
Daniel

**Pull request closed without merging**
