### PR TITLE
LPS-111489

### PR DESCRIPTION
**Pull request by bakayattila**
HI @dacousalr,
Could you review it?
https://issues.liferay.com/browse/LPS-111489

I needed to modify the test case to represent the correct behavior.
The behavior changed according to [PTR-1620](https://issues.liferay.com/browse/PTR-1620) as you proposed.
Best,
Attila

### CODE REVIEW

**Comment by bakayattila** [comment]
#209

**Comment by dacousalr** [comment]
ci:forward

**Comment by dacousalr** [comment]
Thank you for reviewing these tests, @bakayattila

They look good to me.

Forwarding ...

**Comment by dacousalr** [comment]
ci:forward

**Comment by dacousalr** [comment]
ci:forward

**Pull request closed without merging**
