### PR TITLE
[TS] LPS-123159 | master

### PR DESCRIPTION
**Pull request by bakayattila**
Hi @dacousalr,

I reviewed the modification and made the test case according to our discussion.
Could you review it?

https://issues.liferay.com/browse/LPS-123159

Best,
Attila

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/dacousalr/liferay-portal/pull/290. [See changes here.](https://github.com/dacousalr/liferay-portal/compare/0c16ee32c285~2...0c16ee32c285)

**Pull request closed without merging**
