### PR TITLE
Lps 91047

### PR DESCRIPTION
**Pull request by balazssk**
Hi @dacousalr ,

cc @moltam89

https://issues.liferay.com/browse/LPS-91047
I'm not 100% sure this is the best approach, but I couldn't think of anything more user friendly.
If you like the idea, can you please review?

I'm open to any suggestion to the name suffixing format though. Maybe something with actual info instead of just the random String to help the users identify where the SNM was imported from.

Thanks,

### CODE REVIEW

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
Hi @dacousalr ,
I don't see any any correlation between the failed test and my changes.
Can you please review?

Thanks

**Comment by dacousalr** [comment]
Just started reviewing :)

**Pull request closed without merging**
