### PR TITLE
LPS-92709 Allow pass the ddmTemplateKey in the friendlyURL

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/pavel-savinov/liferay-portal/pull/334.

**Pull request closed without merging**
