### PR TITLE
LPS-136108 Retain URL format on export/import whenever possible

### PR DESCRIPTION
**Pull request by mbowerman**
Hi Daniel,

This pull request is to keep the URL formatting consistent during import/export whenever possible (specifically, in cases where the exported URL lacks the servlet mapping and group friendly URL), as we discussed on [PTR-2516](https://issues.liferay.com/browse/PTR-2516).

I'm also including [LPS-136320](https://issues.liferay.com/browse/LPS-136320) with this fix since the fix won't really work properly without it. Note that I retested the issue described in [LPS-106335](https://issues.liferay.com/browse/LPS-106335) after making this commit, and it still behaves correctly.

I tested this pretty thoroughly and am pretty confident that it at least shouldn't cause any regressions. Any time we *can* keep the URL in the "/test-page" format, we do; otherwise, we append the servlet mapping and group friendly URL to it (e.g. "/web/guest/test-page").

One of the more noteworthy changes in this pull request, which could have implications outside of this immediate fix, is to modify the behavior when a URL is exported from the default site that uses the company host. Because the company host functions identically to a Public Pages virtual host for the default site, I modified the behavior such that the URL is modified to use the Public Pages virtual host on the import site (if one exists). This change is handled by commits 9b4d73e39b33d1ed5b1fe9e2167fa592483f1c82 and bd30f9edab2fc7701936a1bdb847d1c2aac1ce27.

Please feel free to let me know if you have any questions.

https://issues.liferay.com/browse/LPS-136108

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:staging

**Comment by mbowerman** [comment]
ci:test:staging

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Hi @mbowerman,

I have found only one case where the group friendly URL is present but it seems that it will be treated in https://issues.liferay.com/browse/LPS-136323, so this PR has passed my review.

Since there is a commit in common with https://github.com/vendeltoreki/liferay-portal/pull/217, please let me know which PR you want to forward first.

**Comment by mbowerman** [comment]
Hi @dacousalr, 

Thanks for the review!

> I have found only one case where the group friendly URL is present but it seems that it will be treated in https://issues.liferay.com/browse/LPS-136323, so this PR has passed my review.

Could you let me know which case that is?

> Since there is a commit in common with vendeltoreki#217, please let me know which PR you want to forward first.

You can forward this one first. I will close https://github.com/vendeltoreki/liferay-portal/pull/217

**Comment by dacousalr** [comment]
> Could you let me know which case that is?

Yes, I was referring to the use of URLs with public pages virtual host and explicit group friendly URL, which is contained in LPS-136323's steps to reproduce.

Forwarding...

**Comment by dacousalr** [comment]
ci:forward

**Comment by mbowerman** [comment]
Hi @dacousalr,

> Yes, I was referring to the use of URLs with public pages virtual host and explicit group friendly URL, which is contained in LPS-136323's steps to reproduce.

Ah, yes, as you found, this case is intended to be fixed in [LPS-136323](https://issues.liferay.com/browse/LPS-136323).

The scope of this ticket ([LPS-136108](https://issues.liferay.com/browse/LPS-136108)) is just to retain the format of URLs that don't include the group friendly URL or servlet mapping. URLs that include the group friendly URL or servlet mapping are not relevant to this ticket (well, so long as we don't introduce any regressions regarding them).

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/dacousalr/liferay-portal/pull/326.

**Pull request closed without merging**
