### PR TITLE
LPS-83494 Semantic Versioning.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by dacousalr** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marianoalvarosaiz** [comment]
Hi @dacousalr,
 did you have time to take a look to the PR? Can I help you with the review?
Kind regards.

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61825. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
