### PR TITLE
LPS-10995 review

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @dacousalr

based on my tests it is working and no regression described here:
https://issues.liferay.com/browse/LPP-36633?focusedCommentId=2113267&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2113267

Could you please push it forward?

Thanks, Roland

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Pull request submitted to https://github.com/p2kmgcl/liferay-portal/pull/592. [See changes here.](https://github.com/dacousalr/liferay-portal/compare/10efc8107ac9~2...10efc8107ac9)

**Pull request closed without merging**
