### PR TITLE
LPS-96554 baseline

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test

**Comment by dacousalr** [comment]
Hi @linolaoj,

Just one question, why the implementation of getLayouts is not redirecting to LayoutLocalServiceImpl to be filtered by permissions afterwards?

**Comment by linolaoj** [comment]
Hi @dacousalr ,
I saw that some implementations of getLayouts use the filterLayouts and others use a "filterFindBy". For the case described on LPS-96554, I had the same result with both so I used the simplest one. If you think it is better to use filterLayouts I can resend.

Thanks!

**Comment by dacousalr** [comment]
I would feel more comfortable if you could resend it with that modification.

Thanks in advance

**Comment by linolaoj** [comment]
Here it is https://github.com/dacousalr/liferay-portal/pull/128

**Pull request closed without merging**
