### PR TITLE
Lps 90925

### PR DESCRIPTION
**Pull request by hudakl**
Hi Daniel,

This is a followup of this pull: https://github.com/dacousalr/liferay-portal/pull/110
I've added the necessary permission check.

Is it OK like this?

thanks,
Laci

### CODE REVIEW

**Comment by dacousalr** [comment]
Hi @hudakl,

That check may leave some case out. There might be users who are allowed to review that are not Content Reviewers.

Could you try with journalArticleAssetRenderer.hasViewPermission(PermissionChecker)?

Closing by now. Feel free to reopen it or sending a new PR.

**Comment by hudakl** [comment]
Hi @dacousalr ,

That's what I tried first, but that didn't solve the problem. The guest could still see the unpublished content.
As I checked the code this method supposed check if the user has a permission to check contents submitted for review.
Indeed it doesn't appear to handle custom reviewer roles, but since hasViewPermission doesn't work this is our best bet for now.

What do you think?

Thanks,
Laci

**Comment by hudakl** [comment]
Hi @dacousalr,

I did some further investigation and I found that there are no permissions assigned to the Reviewer roles and it appears there are no review specific permissions.
This suggests that the reviewer rights are handled at role level similarly to the Admin roles and we can't even define custom reviewer roles.

In light of this I think the approach I suggested if the only one that could work in this scenario.

Do you agree?

Thank you,
Laci

**Comment by dacousalr** [comment]
Hi @hudakl,

Depending on the workflow definition, any role or user can be a potential reviewer so I am afraid we cannot dismiss this.

**Comment by hudakl** [comment]
Hi @dacousalr ,

Do you have any suggestions on how this permission check should be handled?
I didn't find any workflow related permissions which we could use for this check and as I said the hasViewPermission didn't work.

Thank you,
Laci

**Pull request closed without merging**
