### PR TITLE
[TS] LPS-139647 Add upgrade process for deleting wrongly created Layout and LayoutPageTemplateStructures

### PR DESCRIPTION
**Pull request by markgulacsy**
Hello @dacousalr,

This is a follow-up PR of an old PR https://github.com/liferay-echo/liferay-portal/pull/6904
Could you review my changes covering the OracleDB compatibility, please?
If you have any questions please feel free to contact me.

Thank you in advance!

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by markgulacsy** [comment]
Hi @dacousalr,
Thank you!

**Pull request closed without merging**
