### PR TITLE
LPS-108806 buildlang

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Hi @robertoDiaz,

It seems that JournalExportImportTest.testVersioning2 is failing. Could you review it, please?

**Comment by dacousalr** [comment]
Just started reviewing :)

**Pull request closed without merging**
